import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";
import Carousel from "../components/Carousel";
import { Products } from "../types";
import type { GetStaticProps } from "next";

function Home({ products }: { products: any }) {
  return (
    <div id="home" className={styles.container}>
      <Head>
        <title>Etsy Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="content">
        <Carousel products={products} />
        <div id="introduction">
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel, fuga
            dolor esse ab hic aperiam ipsam consequuntur cupiditate veniam dicta
            maiores cum modi asperiores amet omnis quae neque, ut perferendis.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex itaque
            optio maxime dolores placeat? Culpa nisi facilis mollitia ad,
            commodi architecto blanditiis nihil earum suscipit ipsa magnam
            corporis? Nemo, magni. Lorem ipsum, dolor sit amet consectetur
            adipisicing elit. Tempora assumenda repellat distinctio, officiis
            expedita unde, voluptates minus reprehenderit veniam similique, aut
            asperiores magni pariatur vitae voluptatibus odio esse quisquam.
            Natus.
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://fakestoreapi.com/products");
  const products: Products = await res.json();

  return {
    props: {
      products: products,
    },
  };
};

export default Home;
