import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Products } from "../types";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

const Home: NextPage<{ products: Products[] }> = ({ products }) => {
  return (
    <div id="home" className={styles.container}>
      <Head>
        <title>Etsy Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div id="content">
        {products.map((products) => {
          return <li key={products.id}>{products.title}</li>;
        })}
      </div>
      <Footer />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://fakestoreapi.com/products");
  const products: Products = await res.json();

  return {
    props: {
      products: products,
    },
  };
};
export default Home;
