import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Products } from "../types";

const Home: NextPage<{ products: Products[] }> = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Etsy Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {products.map((products) => {
        return <li key={products.id}>{products.title}</li>;
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://fakestoreapi.com/products");
  const products: Products = await res.json();

  return {
    props: {
      products: products,
    },
  };
};
export default Home;
